// SPDX-License-Identifier: LGPL-3.0-only
//
// This file is provided WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.
pragma solidity >=0.8.27;

import { IInterfold } from "../interfaces/IInterfold.sol";

// Auto-generated by scripts/build-circuits.ts for insecure-512/minimum.
library ActiveCryptoConfig {
    uint8 internal constant PARAM_SET = 0;
    bytes32 internal constant PARAM_SET_HASH =
        0x18c6d8650486b997d48aa2d285fae878fb267b268332d056a3e8527d50e87b4f;
    uint8 internal constant COMMITTEE_SIZE = 0;
    uint32 internal constant T = 1;
    uint32 internal constant H = 2;
    uint32 internal constant N = 3;

    function validateCommittee(
        uint8 committeeSize,
        uint32[2] calldata threshold
    ) internal pure {
        if (
            committeeSize != COMMITTEE_SIZE ||
            threshold[0] != H ||
            threshold[1] != N
        ) revert IInterfold.UnsupportedCryptoConfig();
    }

    function validateParamSet(
        uint8 paramSet,
        bytes32 paramSetHash
    ) internal pure {
        if (paramSet != PARAM_SET || paramSetHash != PARAM_SET_HASH)
            revert IInterfold.UnsupportedCryptoConfig();
    }
}
