// SPDX-License-Identifier: LGPL-3.0-only
//
// This file is provided WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.
pragma solidity >=0.8.27;

import { IInterfold } from "../interfaces/IInterfold.sol";

// Auto-generated by scripts/build-circuits.ts for secure-8192/micro.
library ActiveCryptoConfig {
    bytes32 internal constant ENCRYPTION_SCHEME_ID = keccak256("fhe.rs:BFV");
    bytes32 internal constant CIRCUIT_VERSION =
        keccak256("interfold-bfv-v1");
    bytes32 internal constant CONFIG_ID =
        0x17654d80a8bd5631a6f52cc9f86ac091b352ac95943366a8a41e7336e9a920fc;
    uint8 internal constant PARAM_SET = 1;
    bytes32 internal constant PARAM_SET_HASH =
        0x14d06d03810686d4dbb46d63989c664693fe4cd96d78146bcc078b055061536e;
    uint8 internal constant COMMITTEE_SIZE = 1;
    uint32 internal constant T = 4;
    uint32 internal constant H = 5;
    uint32 internal constant N = 9;

    function id() internal pure returns (bytes32) {
        return CONFIG_ID;
    }

    function validateEncryptionScheme(bytes32 encryptionSchemeId) internal pure {
        if (encryptionSchemeId != ENCRYPTION_SCHEME_ID)
            revert IInterfold.UnsupportedCryptoConfig();
    }

    function validateCommittee(
        uint8 committeeSize,
        uint32[2] calldata threshold
    ) internal pure {
        if (
            committeeSize != COMMITTEE_SIZE ||
            threshold[0] != H ||
            threshold[1] != N
        ) revert IInterfold.UnsupportedCryptoConfig();
    }

    function validateParamSet(
        uint8 paramSet,
        bytes32 paramSetHash
    ) internal pure {
        if (paramSet != PARAM_SET || paramSetHash != PARAM_SET_HASH)
            revert IInterfold.UnsupportedCryptoConfig();
    }
}
