#!/usr/bin/env bash

PINATA_JWT=""
IPFS_GATEWAY_URL=""
while [[ $# -gt 0 ]]; do
  case $1 in
    --pinata-jwt)
      PINATA_JWT="$2"
      shift 2
      ;;
    --ipfs-gateway-url)
      IPFS_GATEWAY_URL="$2"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1"
      exit 1
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONTAINER_ARGS=("./scripts/container/upload.sh")

if [[ -n "$PINATA_JWT" ]]; then
  CONTAINER_ARGS+=("--pinata-jwt" "$PINATA_JWT")
fi

if [[ -n "$IPFS_GATEWAY_URL" ]]; then
  CONTAINER_ARGS+=("--ipfs-gateway-url" "$IPFS_GATEWAY_URL")
fi

exec "$SCRIPT_DIR/container" "${CONTAINER_ARGS[@]}"
