[workspace]
members = [
    "pk_generation",
    "pk_aggregation",
    "user_data_encryption",
    "user_data_encryption_ct0",
    "user_data_encryption_ct1",
    "ct0_e0_r2_check",
    "ct0_r1_check",
    "ct0_pk_commit",
    "ct0_ct_commit",
    "ct0_u_k1_check",
    "ct0_ab_combine",
    "ct0_cd_combine",
    "ct0_abcd_combine",
    "ct0_abcde_combine",
    "ct0_eval_e0_r2",
    "ct0_eval_r1",
    "ct0_eval_pk",
    "ct0_eval_ct",
    "ct0_eval_u_k1",
    "ct0_eval_ab_combine",
    "ct0_eval_cd_combine",
    "ct0_eval_abcd_combine",
    "ct0_eval_abcde_combine",
    "ct1_e1_p2_u_check",
    "ct1_p1_check",
    "ct1_pk_commit",
    "ct1_ct_commit",
    "ct1_ab_combine",
    "ct1_cd_combine",
    "ct1_abcd_combine",
    "ct1_eval_e1_p2_u",
    "ct1_eval_p1",
    "ct1_eval_pk",
    "ct1_eval_ct",
    "ct1_eval_ab_combine",
    "ct1_eval_cd_combine",
    "ct1_eval_abcd_combine",
    "share_decryption",
    "decrypted_shares_aggregation",
]