sequenceDiagram
  participant E as EVM
  participant B as EventBus
  participant R as E3Router
  participant W as InterfoldSolWriter
  participant L as LibP2p
  participant P as PlaintextAggregator
  participant M as Multithread(1)

  rect rgb(230, 245, 255)
    Note over P, M: Plaintext Aggregation
    L --) P: DecryptionShareCreated
    L --) P: DecryptionShareCreated
    L --) P: DecryptionShareCreated
    P ->> M: ComputeRequest(TrBFV::ThresholdDecrypt)
    M ->> M: trbfv::calculate_threshold_decryption()
    M ->> P: ComputeResponse(TrBFV::ThresholdDecrypt)
    P ->> B: PlaintextAggregated (local publication intent)
    B ->> W: PlaintextAggregated
    W ->> E: publishPlaintextOutput
    E --) B: PlaintextOutputPublished
    E --) B: E3StageChanged(Complete)
    B --) R: E3StageChanged(Complete)
    R ->> B: E3RequestComplete
    B --) P: E3RequestComplete
  end
  autonumber

