// SPDX-License-Identifier: LGPL-3.0-only
//
// This file is provided WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.

//! Asserts that the Rust input tree reproduces a root a real contract actually produced.
//!
//! The fixture is generated by `tests/input-tree-e2e.test.ts` in `crisp-contracts`, which publishes
//! a real ballot — real BFV ciphertext, real Noir proof — through `publishInput` and records the
//! resulting on-chain `inputRoot`. Regenerate with
//! `UPDATE_INPUT_TREE_FIXTURE=1 pnpm test` in that package.
//!
//! This is the one check that catches a divergence between `CRISPProgram.inputLeaf` and
//! `MerkleTreeBuilder`. Such a divergence makes every round fail with no other symptom, and no
//! single-language test can see it.

use e3_compute_provider::{ComputeInput, FHEInputs};
use e3_fhe_params::{build_pair_for_preset, encode_bfv_params, BfvPreset};
use sha3::Digest as _;

const FIXTURE: &str =
    include_str!("../../../examples/CRISP/packages/crisp-contracts/tests/fixtures/input-tree.json");

fn unhex(value: &str) -> Vec<u8> {
    hex::decode(value.trim_start_matches("0x")).expect("fixture hex")
}

#[test]
fn rust_reproduces_the_root_the_contract_produced() {
    let fixture: serde_json::Value = serde_json::from_str(FIXTURE).expect("fixture json");
    let expected_root = unhex(fixture["inputRoot"].as_str().expect("inputRoot"));

    let entries = fixture["inputs"].as_array().expect("inputs");
    let mut ciphertexts = Vec::new();
    let mut commitments = Vec::new();
    let mut slots = Vec::new();
    for (index, entry) in entries.iter().enumerate() {
        ciphertexts.push((
            unhex(entry["encryptedVote"].as_str().expect("encryptedVote")),
            index as u64,
        ));
        let commitment = unhex(entry["commitment"].as_str().expect("commitment"));
        commitments.push(<[u8; 32]>::try_from(commitment.as_slice()).expect("32-byte commitment"));
        let slot = unhex(entry["slot"].as_str().expect("slot"));
        slots.push(<[u8; 20]>::try_from(slot.as_slice()).expect("20-byte slot"));
    }

    // The SDK builds ballots under the insecure-512 threshold preset.
    let (params, _) = build_pair_for_preset(BfvPreset::InsecureThreshold512).unwrap();
    let result = ComputeInput {
        fhe_inputs: FHEInputs {
            ciphertexts,
            commitments,
            slots,
            params: encode_bfv_params(&params),
        },
    }
    .process(|inputs| {
        // Membership of the tree is what this test asserts, so the processor only has to be
        // deterministic over the usable set.
        inputs
            .ciphertexts
            .iter()
            .flat_map(|(bytes, _)| bytes.clone())
            .collect()
    })
    .expect("the fixture round must process");

    assert_eq!(
        hex::encode(&result.merkle_root),
        hex::encode(&expected_root),
        "the Rust input tree diverged from the root CRISPProgram produced"
    );
}

/// The TypeScript SDK and Rust must agree on `compute_ct_commitment`, or the Secure Process would
/// reject every honest input as contradicting its commitment.
#[test]
fn the_sdk_and_rust_agree_on_the_ciphertext_commitment() {
    let fixture: serde_json::Value = serde_json::from_str(FIXTURE).unwrap();
    let entry = &fixture["inputs"][0];
    let bytes = unhex(entry["encryptedVote"].as_str().unwrap());
    let stored = unhex(entry["commitment"].as_str().unwrap());

    let (params, _) = build_pair_for_preset(BfvPreset::InsecureThreshold512).unwrap();
    let recomputed = e3_bfv_client::client::compute_ct_commitment(
        bytes,
        params.degree(),
        params.plaintext(),
        params.moduli().to_vec(),
    )
    .expect("a ciphertext the SDK produced must deserialize");

    assert_eq!(
        hex::encode(recomputed),
        hex::encode(&stored),
        "the SDK commitment and the Rust commitment diverged"
    );
}

const APPEND_FIXTURE: &str = include_str!(
    "../../../examples/CRISP/packages/crisp-contracts/tests/fixtures/input-tree-append.json"
);

/// The poisoning case, against a tree a real contract built.
///
/// The fixture holds two entries for one slot: an honest ballot, then a genuine mask proof
/// published beside bytes that are not the summed ciphertext it proved. The Secure Process must
/// reproduce the on-chain root over both entries, and fall back to the honest one.
#[test]
fn rust_falls_back_to_the_last_good_entry_in_a_slot() {
    let fixture: serde_json::Value = serde_json::from_str(APPEND_FIXTURE).expect("fixture json");
    let expected_root = unhex(fixture["inputRoot"].as_str().expect("inputRoot"));
    let honest_index = fixture["honestIndex"].as_u64().expect("honestIndex") as usize;

    let entries = fixture["inputs"].as_array().expect("inputs");
    let mut ciphertexts = Vec::new();
    let mut commitments = Vec::new();
    let mut slots = Vec::new();
    for (index, entry) in entries.iter().enumerate() {
        ciphertexts.push((
            unhex(entry["encryptedVote"].as_str().unwrap()),
            index as u64,
        ));
        commitments.push(
            <[u8; 32]>::try_from(unhex(entry["commitment"].as_str().unwrap()).as_slice()).unwrap(),
        );
        slots
            .push(<[u8; 20]>::try_from(unhex(entry["slot"].as_str().unwrap()).as_slice()).unwrap());
    }
    assert_eq!(entries.len(), 2, "the fixture must hold both entries");
    assert_eq!(slots[0], slots[1], "both entries belong to one slot");

    let honest_bytes = ciphertexts[honest_index].0.clone();
    let (params, _) = build_pair_for_preset(BfvPreset::InsecureThreshold512).unwrap();

    // The processor records what it was handed, so the selection is observable.
    let result = ComputeInput {
        fhe_inputs: FHEInputs {
            ciphertexts,
            commitments,
            slots,
            params: encode_bfv_params(&params),
        },
    }
    .process(|inputs| {
        inputs
            .ciphertexts
            .iter()
            .flat_map(|(bytes, _)| bytes.clone())
            .collect()
    })
    .expect("a poisoned append must not stop the round");

    assert_eq!(
        hex::encode(&result.merkle_root),
        hex::encode(&expected_root),
        "the Rust input tree diverged from the root CRISPProgram produced"
    );

    // The processor saw exactly the honest ballot: the poisoned append was skipped, and the entry
    // it tried to replace survived.
    assert_eq!(
        result.ciphertext_hash,
        sha3::Keccak256::digest(&honest_bytes).to_vec(),
        "the Secure Process must fall back to the slot's last good entry"
    );
}
